service: ./services/infrastructure
useDotenv: true

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-jest-plugin
  - serverless-offline

custom:
  bundle:
    excludeFiles: '**/*.test.ts'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221

  environment:
    NODE_ENV: ${env:NODE_ENV}

functions:
  health:
    handler: src/health.health
    events:
      - http:
          path: health
          method: get
  foo:
    handler: src/foo.foo
    events:
      - http:
          path: foo
          method: post
